#include "../lib/qjswrapper.hpp"
#include "../js/ship.h" // Generated bytecode
#include <iostream>

class Ship {
public:
    Ship(std::string name, int fuel) : name(name), fuel(fuel) {
        std::cout << "[C++] Ship '" << name << "' constructed with " << fuel << " fuel.\n";
    }

    void fly(int distance) {
        if (fuel >= distance) {
            fuel -= distance;
            std::cout << "[C++] " << name << " flew " << distance << " units. Fuel left: " << fuel << "\n";
        } else {
            std::cout << "[C++] " << name << " out of fuel!\n";
        }
    }

    int get_fuel() const { return fuel; }
    std::string get_name() const { return name; }

    std::string name;
    int fuel;
};

void add_console_utilities(qjs::Engine& engine) {
    auto global = engine.get_global_object();
    auto console = engine.create_object("console");

    console.register_function("log", [](std::string msg) {
        std::cout << "[JS] " << msg << std::endl;
    });
}

int main() {
    qjs::Engine engine;

    add_console_utilities(engine);

    auto global = engine.get_global_object();

    global.register_class<Ship>("Ship")
        .constructor([](const std::string& name, int fuel) {
            auto s = new Ship(name, fuel);
            return s;
        })
        .method("fly", &Ship::fly)
        .method("refuel", [](Ship* s, int amount) {
            s->fuel += amount;
            std::cout << s->name << " refueled by " << amount << std::endl;
        })
        .method("getFuel", &Ship::get_fuel)
        .method("getName", &Ship::get_name)
        .field("fuel", &Ship::fuel)
        .field("name", &Ship::name);
    
    if (auto result = engine.run_bytecode(qjsc_ship, qjsc_ship_size); !result) {
        std::cerr << "Script Error: " << result.error() << "\n";
    }
    return 0;
}