#include "../lib/qjswrapper.hpp"
#include "../js/ship.h" // Generated bytecode
#include <iostream>
#include <cassert>

class Ship {
public:
    Ship(std::string name, int fuel) : name(name), fuel(fuel) {}

    void fly(int distance) {
        if (fuel >= distance) {
            fuel -= distance;
        }
    }

    int get_fuel() const { return fuel; }
    std::string get_name() const { return name; }

    std::string name;
    int fuel;
};

void add_console_utilities(qjs::Engine& engine) {
    auto global = engine.get_global_object();
    auto console = engine.create_object("console");

    console.register_function("log", [](std::string msg) {
        std::cout << "[JS] " << msg << std::endl;
    });
}

int main() {
    qjs::Engine engine;
    add_console_utilities(engine);

    auto global = engine.get_global_object();

    // Register the Ship class
    global.register_class<Ship>("Ship")
        .constructor([](const std::string& name, int fuel) {
            return new Ship(name, fuel);
        })
        .method("fly", &Ship::fly)
        .method("refuel", [](Ship* s, int amount) {
            s->fuel += amount;
        })
        .method("getFuel", &Ship::get_fuel)
        .method("getName", &Ship::get_name)
        .field("fuel", &Ship::fuel)
        .field("name", &Ship::name);
    
    // Execute the bytecode generated from ship.js
    auto result = engine.run_bytecode(qjsc_ship, qjsc_ship_size);
    
    if (!result) {
        std::cerr << "Script Error: " << result.error() << "\n";
        return 1; // Exit with error for CI
    }

    // CI Verification: Run a validation script to check final state
    // ship.js ends with 20 fuel (10 start + 30 refuel - 20 fly)
    auto validation = engine.eval_global("voyager.getFuel()", "verify.js");
    
    if (!validation) {
        std::cerr << "Validation failed to execute: " << validation.error() << "\n";
        return 1;
    }

    if (*validation != "20") {
        std::cerr << "Assertion Failed: Expected fuel 20, but got " << *validation << "\n";
        return 1; // Fails the GitHub Action step
    }

    std::cout << "Test Ship: PASSED\n";
    return 0; // Success
}