name: QJSWrapper Tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: clang
          - os: windows-latest
            toolchain: clang-cl
          - os: macos-latest
            toolchain: clang

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Setup Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libc++-dev libc++abi-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: Configure and Build
        run: |
          # Use the toolchain defined in the matrix
          xmake f -y --toolchain=${{ matrix.toolchain }}
          xmake -y

      - name: Run Math Tests
        run: xmake run unit-tests