name: QJSWrapper Tests

on: [push, pull_request]

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Configure and Build
        run: xmake -y
      - name: Run Math Tests
        run: xmake run unit-tests
  mac-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Configure and Build
        run: xmake -y
      - name: Run Math Tests
        run: xmake run unit-tests