name: Unit Tests
concurrency:
  group: Unit Tests
  cancel-in-progress: false

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${matrix.os}
    steps:
      - uses: actions/checkout@v6
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          actions-cache-key: ${{ runner.os }}-xmake-${{ hashFiles('xmake.lua') }}
      - name: Regenerate Header
        run: xmake amalgamate
      - name: Check for Changes
        run: git diff --exit-code include/qjswrapper.hpp
      - name: Run Unit Tests
        run: xmake run unit-tests